include(${CMAKE_CURRENT_LIST_DIR}/../utils.cmake)

file(READ "${DEPENDENCY_JSON_FILE}" DEP_JSON_STRING)
download_open_source("${OPENSOURCE_COMPONENT_NAME}" "${FILE_GLOB_PATTERN}" "${THIRD_PARTY_CACHE_DIR}")

set(THREAD_NUM "${THREAD_NUM}") # clean warning
if(EXISTS "${LIBBOUNDSCHECK_OUTPUT_DIR}/lib/libboundscheck.so")
    message(STATUS "${OPENSOURCE_COMPONENT_NAME} already built, skipping.")
    return()
endif()

set(PKG_DOWNLOAD_DIR "${THIRD_PARTY_SRC_DIR}/${OPENSOURCE_COMPONENT_NAME}")
execute_process(
    COMMAND make -j${THREAD_NUM}
    WORKING_DIRECTORY ${PKG_DOWNLOAD_DIR} OUTPUT_QUIET
)

file(MAKE_DIRECTORY "${LIBBOUNDSCHECK_OUTPUT_DIR}/include")
file(MAKE_DIRECTORY "${LIBBOUNDSCHECK_OUTPUT_DIR}/lib")
file(COPY "${PKG_DOWNLOAD_DIR}/include/" DESTINATION "${LIBBOUNDSCHECK_OUTPUT_DIR}/include")
file(COPY "${PKG_DOWNLOAD_DIR}/lib/libboundscheck.so" DESTINATION "${LIBBOUNDSCHECK_OUTPUT_DIR}/lib")
message(STATUS "${OPENSOURCE_COMPONENT_NAME} has been successfully built and installed to ${LIBBOUNDSCHECK_OUTPUT_DIR}")
