#!/usr/bin/env python
# coding=utf-8
# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# MindIE is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

from atb_llm.nn.fusion_pass_base import FusionPassBase
from atb_llm.nn.tensor import Tensor
from atb_llm.nn.node import Node
from atb_llm.utils.quantize.pack_type import DataType


HAS_BIAS = "hasBias"


class W8A8LinearWitBiasDequantPerTensorPass(FusionPassBase):
    """
    This fusion pass identifies a pattern of two consecutive nodes: a matmul node and a dequant node,
    which is replaced by a single fusion node.

    When performing inference on quantized models, activations and weights are quantized before
    the matmul operation to reduce memory usage and accelerate inference. During the matmul operation,
    the quantized int8 input tensors are computed, and the result is then dequantized to a floating-point type
    using the quantization parameters.

    This fusion pass is suitable for per-tensor quantization algorithms. The quantization parameters
    for both activations and weights are generated by an offline algorithm,
    and the output quantization parameters are pre-processed to simplify the actual inference process.
    """
    def __init__(self):
        """
        This fusion pass will be automatically applied to the following calculations:

        weight = nn.Parameter(prefix="model", suffix="weight")
        deq_scale = nn.Parameter(prefix="model", suffix="deq_scale")
        quant_bias = nn.Parameter(prefix="model", suffix="quant_bias")

        output_dtype = DataType.ACL_BF16 if dtype == torch.bfloat16 else DataType.ACL_FLOAT16
        out = nn.functional.matmul(
            input_tensor, weight.get_tensor(),
            transpose_b=True)
        out = nn.quantized.dequantize(
            out, deq_scale.get_tensor(), output_dtype=output_dtype, bias=quant_bias.get_tensor())

        This fusion pass must be enabled in W8A8 quantization.
        """
        super().__init__()
        # input
        input_tensor = Tensor()
        weight = Tensor()
        deq_scale = Tensor()
        quant_bias = Tensor()
        # output
        out = Tensor()
        # internal
        linear_out = Tensor()

        # nodes before fusing
        param = {HAS_BIAS: False}
        node_linear = Node("Linear", param, [input_tensor, weight], [linear_out])
        self.nodes_before_fusing.append(node_linear)
        param = {
          "hasActivateScale": False,
          HAS_BIAS: True
        }
        node_dequant = Node("DequantBias", param, [linear_out, deq_scale, quant_bias], [out])
        self.nodes_before_fusing.append(node_dequant)

        # node after fusing
        inputs = [input_tensor, weight, deq_scale, quant_bias]
        param = {
            HAS_BIAS: True,
            "hasPerTokenScale": False
        }
        linear_dequant_node = Node('W8A8MatMul', param, inputs, [out])
        self.nodes_after_fusing.append(linear_dequant_node)

    def _check_param_by_pass(self, target_graph: list[Node]) -> bool:
        first_node_param_match = not target_graph[0].op_param[HAS_BIAS] and \
            not target_graph[0].op_param['transposeA']
        second_node_param_match = not target_graph[1].op_param['hasActivateScale'] and \
            target_graph[1].op_param[HAS_BIAS]
        if first_node_param_match and second_node_param_match:
            return True
        return False

    def _update_param_by_pass(self, target_graph, nodes_after_fusing_for_return):
        # linear
        nodes_after_fusing_for_return[0].op_param["transposeB"] = \
            target_graph[0].op_param.get("transposeB", True)
        # dequant
        if target_graph[1].op_param.get("outputDtype", DataType.ACL_DT_UNDEFINED) == DataType.ACL_FLOAT16:
            nodes_after_fusing_for_return[0].op_param["isBF16"] = False
